# This workflow runs on each update to a pull request to build and then test the app.
name: 'Build and Test'
on: pull_request

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Setup Android problem matchers
        uses: jonasb/android-problem-matchers-action@v1
      - run: ./gradlew assemble

  unit-test:
    name: 'Unit Test'
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Setup Android problem matchers
        uses: jonasb/android-problem-matchers-action@v1
      - run: ./gradlew test